### ISSUE TITLE
eclipse运行还是有问题啊，sql文件里面的表名是小写的呢

### ISSUE THREAD

**Issue by netgb** [kingston-csj/jforgame#10]
Table 'game_data_001.ConfigPlayerLevel' doesn't exist
eclipse运行还是有问题啊，sql文件里面的表名是小写的呢

**Comment by kingston-csj** [comment]
估计是mysql设置问题，windows下不区分大小写。linux下可能区分大小写。建议改下mysql配置试试。
show variables like "%case%";

    lower_case_table_names = 1  表名存储在磁盘是小写的，但是比较的时候是不区分大小写
    lower_case_table_names=0  表名存储为给定的大小和比较是区分大小写的 
    lower_case_table_names=2, 表名存储为给定的大小写但是比较的时候是小写的

**Comment by netgb** [comment]
是的，是linux系统区分大小写问题，用debian运行的服务端，我把项目的sql脚本表名改成驼峰形式，删除之前建立的数据库，重新执行sql脚本暂时解决了问题能运行了
