### ISSUE TITLE
兄弟， 你用了1万中加载配置文件的方法

### ISSUE THREAD

**Issue by Terrency** [kingston-csj/jforgame#13]
JAXPConfigurator.configure
DocumentBuilder.parse
Properties.load
proxool-config.SYSTEM
这样会对不同编辑器的兼容度不够啊

**Comment by kingston-csj** [comment]
不知道你在说什么

**Comment by 1144042967** [comment]
意思是指，不同的编辑器在对应不同的方法时，可能会做不同处理。在idea上能读的文件，放到其他编辑环境，可能就不能读取了。最好读取入口统一，方便排查错误。

**Comment by kingston-csj** [comment]
这个文件不能直接从网络读取。直接在根目录下新建一个配置目录，不同ide应该读取得到的吧。没试过，所以也不确定。如果有问题，希望提供下方案。(^_^)a
