### ISSUE TITLE
配置表 表名大小写问题

### ISSUE THREAD

**Issue by iSenninha** [kingston-csj/jforgame#2]
- 导入的data sql里表名非驼峰命名方式，比如configconstant;
- 但是在代码里的sql的表名是驼峰的
```
String sql = "SELECT * FROM ConfigConstant";
```
导致启动的时候找不到表报错：
```
java.sql.SQLSyntaxErrorException: Table 'game_data_001.ConfigConstant' doesn't exist
```
我这边是Debian，mysql大小写敏感了。
谢谢楼主开源～

**Comment by kingston-csj** [comment]
sql文件表名大小写已修正跟代码保持一致，多谢提醒！！

**Comment by netgb** [comment]
Table 'game_data_001.ConfigPlayerLevel' doesn't exist
eclipse运行还是有问题啊，sql文件里面的表名是小写的呢？
