### ISSUE TITLE
使用IDEA运行项目失败，有报错

### ISSUE THREAD

**Issue by owllyi** [kingston-csj/jforgame#24]
使用的是IDEA 2021.1版本，Java环境是：Java(TM) SE Runtime Environment (build 1.8.0_181-b13)

打开工程后自动下载maven相关插件，然后就报错了：
Cannot resolve org.apache.mina:mina-core:2.0.7

看了下pom.xml里面也有org.apache.felix相关的plugin，不知道是哪里的问题，麻烦看下该如何配置吧。

我直接点了build，提示缺少包：
D:\Src\jforgame\hotswap\hotswap-util\src\main\java\jforgame\hotswap\HotSwapUtil.java:3:28
java: 程序包com.sun.tools.attach不存在

请问是因为上面的报错导致没下载完全么，还是需要进行什么设置，或者安装特殊的jdk呢？

**Comment by kingston-csj** [comment]
第一个可以尝试把maven仓库下的mina删了重新下载；
第二个看下java环境变量是不是用了jre，而不是jdk。

**Comment by owllyi** [comment]
第一个问题已经把.m2目录下的felix和mina目录删除了重新下载了，还是有这个提示。我把aliyun的仓库注释了再更新，还是报错。

第二个我看了下，环境变量设置的是JDK。
CLASSPATH .;%JAVA_HOME%\bin;%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar
JAVA_HOME C:\Program Files\Java\jdk1.8.0_181

应该没什么问题吧

**Comment by owllyi** [comment]
报错信息：
Could not find artifact org.apache.mina:mina-core:bundle:2.0.7 in central (https://repo.maven.apache.org/maven2)

**Comment by kingston-csj** [comment]
你是不是idea里面的maven插件版本不兼容啊。直接试下命令行 mvn clean package install -DskipTests吧。不行的话我也没办法了，自行百度把。

**Comment by owllyi** [comment]
经过各种配置，已经运行起来了，谢谢

**Comment by hejiang123** [comment]
请问怎么配置的第一个错误。我下载了个文件导入mvn  都还不行
