### ISSUE TITLE
onekey.sh运行报错，缺少jar包

### ISSUE THREAD

**Issue by mingjia1** [kingston-csj/jforgame#27]
_Downloading: https://repo.maven.apache.org/maven2/org/jforgame/jforgame-common/1.0.0/jforgame-common-1.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/jforgame/jforgame-net/1.0.0/jforgame-net-1.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/jforgame/jforgame-orm/1.0.0/jforgame-orm-1.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/jforgame/hotswap-util/1.0.0/hotswap-util-1.0.0.jar_
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:24.025s
[INFO] Finished at: Thu Jan 06 16:33:04 CST 2022
[INFO] Final Memory: 11M/130M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jforgame-server: Could not resolve dependencies for project org.jforgame:jforgame-server:jar:1.0.0: The following artifacts could not be resolved: org.jforgame:jforgame-common:jar:1.0.0, org.jforgame:jforgame-net:jar:1.0.0, org.jforgame:jforgame-orm:jar:1.0.0, org.jforgame:hotswap-util:jar:1.0.0: Could not find artifact org.jforgame:jforgame-common:jar:1.0.0 in public (http://maven.aliyun.com/nexus/content/groups/public/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

缺少 jforgame-net-1.0.0.jar类似的jar包

**Comment by kingston-csj** [comment]
在项目根目录下，执行mvn clean package install -DskipTests 。就会把模块依赖下载安装到本地依赖。你再试下，讲道理是可以的。
