### ISSUE TITLE
jforgame-server/pom.xml 遇到一个编译错误

### ISSUE THREAD

**Issue by Zering** [kingston-csj/jforgame#3]
![jforgame](https://user-images.githubusercontent.com/14093175/36891901-00a0fd66-1e3e-11e8-9a15-69903afd0750.jpg)

把项目导入idea之后,jforgame-server/pom.xml遇到了一个编译错误,如上图;

本地maven版本3.3.9,更新到最新的3.5.2之后还是显示错误;

然后查看了一下 [apache maven 官网](http://maven.apache.org/shared-archives/maven-archiver-LATEST/examples/manifest.html),,然后我直接删除了这一行,请问一下这个应该对打jar包没有影响的吧？

**Comment by iSenninha** [comment]
去掉这个打出来的jar包名字估计就是**game-0.0.1-SNAPSHOT.jar**，然后[启动脚本](https://github.com/kingston-csj/jforgame/blob/union/admin.sh)里的jar包名字也要跟着改了..

**Comment by kingston-csj** [comment]
我本地maven的版本也是3.3.9，没遇见到类似报错。如果影响编译，去掉那行也没关系，它只是为脚本打出的包起个名字而已。在开发环境，甚至不需要用到打包脚本^_^。
