### ISSUE TITLE
C#客户端通信

### ISSUE THREAD

**Issue by jingChou91** [kingston-csj/jforgame#8]
请问如果用C#写的客户端 比如unity3D 该怎么与之通信？ C#没法直接用NioSocketConnector IoSession之类的

**Comment by kingston-csj** [comment]
服务端客户端采用不用的语言，这是很正常的。只要客户端支持socket就可以，通信双方是基于byte数据流的。c#可以用socket进行底层封装，构造iosession。

**Comment by jingChou91** [comment]
>           服务端客户端采用不用的语言，这是很正常的。只要客户端支持socket就可以，通信双方是基于byte数据流的。c#可以用socket进行底层封装，构造iosession。

我尝试用C#发消息，debug后发现是到MinaDecoder的decode(IoSession session, IoBuffer in, ProtocolDecoderOutput out)时  走的//数据包不完整，继续等待数据到达 这个判断分支。我看java是发消息是extends Message，C#那边发消息编码该如何extends Message（主要这个我没试出来）以便复用你的服务端代码？

**Comment by kingston-csj** [comment]
建议看下 https://blog.csdn.net/littleschemer/article/details/73555975 这篇文章。里面有说明这个框架所使用的 **私有协议栈**。重点看下 消息包和消息体是由哪些部分拼成的。

**Comment by jingChou91** [comment]
您好 这篇文章我看了  我也看了你定义MinaDecoder和MinaEncoder，java这边我是能看懂的。   我想请教下 你说用C#封装socket，构造iosession，这个该如何做。因为我不太会C#，网上也找不到这块内容，所以比较困惑。

**Comment by kingston-csj** [comment]
我也不会c#，session只是一个方便io通信的工具而已。不用也是可以的。
